image: node:latest

stages:
  - build
  - format
  - lint
  - test

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
formating:
  stage: format
  script:
    - npm install -g husky lint-staged
    - npm run format

eslint:
  stage: lint
  script:
    # Install ESLint in this docker container
    - npm install -g eslint
    # Configure ESLint (will read your .eslintrc file)
    #- eslint --init
    # Run ESLint
    - eslint ./app/*

testing_testing:
  stage: test
  coverage: [^|]*\|[^|]*\s+([\d\.]+)
  script: npm test
  artifacts:
      paths:
      - coverage/
